### PR TITLE
Fix a few typing issues

### PR DESCRIPTION
**Pull request by Avasam**
Ref https://github.com/python/typeshed/pull/9308

### CODE REVIEW

**Comment by Avasam** [comment]
@Kalmat There you go! Hope you can learn a useful thing or two from this :)

**Comment by Kalmat** [comment]
Thanks! I will try to remember to place all typing stuff next time, but not sure if I will be able to do it right, to be honest. In fact, I was trying to fix _linux module, which is the one I modified the most, but I've been unable, sorry. At least now I have a string to pull.

**Comment by Avasam** [comment]
No problem! If you're stuck with types, don't hesitate to checkout 

https://github.com/python/typeshed#discussion

> If you have general questions about typing with Python, or you need a review of your type annotations or stubs outside of typeshed, head over to [our discussion forum](https://github.com/python/typing/discussions). For less formal discussion, try the typing chat room on [gitter.im](https://gitter.im/python/typing). Some typeshed maintainers are almost always present; feel free to find us there and we're happy to chat. Substantive technical discussion will be directed to the issue tracker.

**Comment by Kalmat** [comment]
I will! (be stuck and checkout... Hahaha!)

Thank you!

**Pull request merged**
