### PR TITLE
Update pyrightconfig and unused ignore comments

### PR DESCRIPTION
**Pull request by Avasam**
Just a small update now that pyright allows completely ignoring `type: ignore` comments (leaving them to mypy).

### CODE REVIEW

**Comment by Kalmat** [comment]
So sad I just drafted a new realease and uploaded a new version to PyPi!!! Well, this will be included in next version.

Thank you again!

**Comment by Avasam** [comment]
Don't worry, it does not affect anything on the users' side.

**Comment by Kalmat** [comment]
👍

**Comment by Avasam** [comment]
To avoid having typing extensions be a runtime requirements. You can do the following:
```py
from typing import Any
try:
  from typing_extensions import Literal
except ImportError:
  Literal = Any # Only needed if the import from typing_extensions is used outside of annotations
```

OR

```py
from typing import Any, TYPE_CHECKING
if TYPE_CHECKING:
  from typing_extensions import Literal
else:
  Literal = Any # Only needed if the import from typing_extensions is used outside of annotations
```

**Comment by Kalmat** [comment]
Thank you! "Brown paper bag" version is coming... Hahaha!

**Pull request merged**
